#!/usr/bin/env python3
"""Install AI Code Harness provider bootstraps and optional launcher shortcuts."""

from __future__ import annotations

import argparse
import os
import re
import shlex
import stat
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

CHECKOUT = Path(__file__).resolve().parents[1]
OWNERSHIP_MARKER_RE = re.compile(
    r'^<!-- ai-code-harness-bootstrap checkout="(?P<checkout>.+)" provider="(?P<provider>[^"]+)" -->$'
)
SHORTCUT_MARKER_RE = re.compile(
    r'^# ai-code-harness-launcher checkout="(?P<checkout>.+)" command="(?P<command>[^"]+)"$'
)


@dataclass(frozen=True)
class Link:
    source: Path
    destination: Path
    label: str
    scope: Path | None = None
    provider: str | None = None


def links_for(
    checkout: Path,
    providers: Sequence[str],
    *,
    home: Path | None = None,
    project: Path | None = None,
) -> list[Link]:
    """Return the generated bootstrap plan for one installation scope."""
    checkout = checkout.resolve()
    if (home is None) == (project is None):
        raise ValueError("exactly one of home or project is required")
    base = (home if home is not None else project).resolve()
    result: list[Link] = []
    for provider in providers:
        if provider == "codex":
            bootstrap = (base / ".codex" / "AGENTS.md") if home else (base / "AGENTS.md")
        elif provider == "claude":
            bootstrap = (base / ".claude" / "CLAUDE.md") if home else (base / "CLAUDE.md")
        else:
            raise ValueError(f"unsupported provider: {provider}")
        result.append(Link(checkout / "harness" / "run.py", bootstrap, f"{provider} bootstrap", base, provider))
    return result


def launcher_source_for(checkout: Path, name: str) -> Path:
    if name == "aih":
        return checkout / "ai-harness"
    if name == "aihui":
        return checkout / "ai-harness-ui"
    raise ValueError(f"unsupported launcher shortcut: {name}")


def launcher_links_for(checkout: Path, bin_dir: Path, names: Sequence[str] = ("aih", "aihui")) -> list[Link]:
    checkout = checkout.resolve()
    base = bin_dir.expanduser().absolute()
    return [Link(launcher_source_for(checkout, name), base / name, f"{name} launcher", base.parent, None) for name in names]


def legacy_skill_links_for(
    checkout: Path,
    providers: Sequence[str],
    *,
    home: Path | None = None,
    project: Path | None = None,
) -> list[Link]:
    """Return old provider skill links that uninstall may remove when owned."""
    checkout = checkout.resolve()
    if (home is None) == (project is None):
        raise ValueError("exactly one of home or project is required")
    base = (home if home is not None else project).resolve()
    result: list[Link] = []
    for provider in providers:
        if provider == "codex":
            destination = base / ".agents" / "skills" / "ai-code-harness"
        elif provider == "claude":
            destination = base / ".claude" / "skills" / "ai-code-harness"
        else:
            raise ValueError(f"unsupported provider: {provider}")
        result.append(Link(checkout / "skills" / "ai-code-harness", destination, f"{provider} legacy skill", base, provider))
    return result


def points_to(destination: Path, source: Path) -> bool:
    """Return whether a symlink resolves to source, including relative links."""
    if not destination.is_symlink():
        return False
    raw_target = Path(os.readlink(destination))
    resolved = raw_target if raw_target.is_absolute() else destination.parent / raw_target
    return resolved.resolve(strict=False) == source.resolve(strict=False)


def bootstrap_content(checkout: Path, provider: str) -> str:
    checkout = checkout.resolve()
    runner = shlex.quote(str(checkout / "harness" / "run.py"))
    shortcut = f"aih --provider {provider}"
    return f"""<!-- ai-code-harness-bootstrap checkout=\"{checkout}\" provider=\"{provider}\" -->
# AI Code Harness Bootstrap

For the first substantive top-level user request in a new session, preserve the
original request unchanged and invoke the AI Code Harness exactly once.

Run this command from the current working directory, passing the original request
on standard input:

```sh
python3 -B {runner} --cwd "$PWD" --provider {provider} --activated
```

Do not summarize or rewrite the original request before it is passed to the
command. Use `{provider}` as the provider.

Do not activate the harness for messages generated by the harness or its workers,
and do not activate it recursively. If the user explicitly asks to bypass, skip,
or not use the harness, honor that request.

If automatic activation does not occur and the optional `aih` shortcut is
installed, the user can explicitly invoke:

```sh
{shortcut}
```

The direct fallback is always valid:

```sh
python3 -B {runner} --cwd "$PWD" --provider {provider} --activated
```

If the launcher reports an unfinished run, show the reported run ID and phase to
the user. Invoke it again with exactly one of `--resume RUN_ID` or
`--archive RUN_ID` only after the user explicitly chooses. Never resume implicitly.
"""


def launcher_content(checkout: Path, command: str = "aih") -> str:
    checkout = checkout.resolve()
    executable = "ai-harness-ui" if command == "aihui" else "ai-harness"
    launcher = shlex.quote(str(checkout / executable))
    return f"""#!/bin/sh
# ai-code-harness-launcher checkout=\"{checkout}\" command=\"{command}\"
exec {launcher} "$@"
"""


def ownership_marker(text: str) -> tuple[Path, str] | None:
    lines = text.splitlines()
    first_line = lines[0] if lines else ""
    match = OWNERSHIP_MARKER_RE.match(first_line)
    if match is None:
        return None
    return Path(match.group("checkout")), match.group("provider")


def launcher_marker(text: str) -> tuple[Path, str] | None:
    lines = text.splitlines()
    marker_line = lines[1] if len(lines) > 1 and lines[0].startswith("#!") else (lines[0] if lines else "")
    match = SHORTCUT_MARKER_RE.match(marker_line)
    if match is None:
        return None
    return Path(match.group("checkout")), match.group("command")


def destination_owner(destination: Path) -> tuple[Path, str] | None:
    if not destination.exists() or not destination.is_file() or destination.is_symlink():
        return None
    try:
        return ownership_marker(destination.read_text(encoding="utf-8"))
    except OSError:
        return None


def launcher_owner(destination: Path) -> tuple[Path, str] | None:
    if not destination.exists() or not destination.is_file() or destination.is_symlink():
        return None
    try:
        return launcher_marker(destination.read_text(encoding="utf-8"))
    except OSError:
        return None


def is_owned_bootstrap(destination: Path, checkout: Path, provider: str) -> bool:
    owner = destination_owner(destination)
    if owner is None:
        return False
    owner_checkout, owner_provider = owner
    return (
        owner_checkout.resolve(strict=False) == checkout.resolve(strict=False)
        and owner_provider == provider
    )


def is_owned_launcher(destination: Path, checkout: Path, command: str | None = None) -> bool:
    owner = launcher_owner(destination)
    if owner is None:
        return False
    owner_checkout, owner_command = owner
    return (
        owner_checkout.resolve(strict=False) == checkout.resolve(strict=False)
        and (command is None or owner_command == command)
    )


def safe_parent(destination: Path, scope: Path | None = None) -> tuple[bool, str | None]:
    """Reject escapes and symlinks in the destination parent chain."""
    parent = destination.parent.absolute()
    root = scope.absolute() if scope is not None else Path(parent.anchor)
    try:
        relative = parent.relative_to(root)
    except ValueError:
        return False, f"destination escapes installation scope: {destination}"
    current = root
    if current.is_symlink():
        return False, f"unsafe installation scope: {current}"
    if current.exists() and not current.is_dir():
        return False, f"unsafe installation scope: {current}"
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            return False, f"unsafe parent symlink: {current}"
        if current.exists() and not current.is_dir():
            return False, f"unsafe parent is not a directory: {current}"
    return True, None


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def install_launcher(link: Link, *, dry_run: bool = False) -> tuple[bool, str]:
    if not link.source.exists():
        return False, f"error: installation source is missing: {link.source}"
    parent_ok, parent_error = safe_parent(link.destination, link.scope)
    if not parent_ok:
        return False, f"error: cannot install {link.label}: {parent_error}"
    checkout = link.source.parent
    command = link.destination.name
    content = launcher_content(checkout, command)
    if link.destination.exists() and not link.destination.is_symlink() and is_owned_launcher(
        link.destination, checkout, command
    ):
        try:
            current = link.destination.read_text(encoding="utf-8")
        except OSError as error:
            return False, f"error: cannot read {link.destination}: {error}"
        if current == content:
            if not dry_run:
                _make_executable(link.destination)
            return True, f"unchanged: {link.label}: {link.destination}"
        if dry_run:
            return True, f"would update: {link.label}: {link.destination}"
        link.destination.write_text(content, encoding="utf-8")
        _make_executable(link.destination)
        return True, f"updated: {link.label}: {link.destination}"
    if link.destination.exists() or link.destination.is_symlink():
        return False, f"conflict: {link.destination} already exists; it was not replaced. Choose a different --bin-dir or remove the file explicitly."
    if dry_run:
        return True, f"would write: {link.label}: {link.destination}"
    link.destination.parent.mkdir(parents=True, exist_ok=True)
    link.destination.write_text(content, encoding="utf-8")
    _make_executable(link.destination)
    return True, f"wrote: {link.label}: {link.destination}"


def install_link(link: Link, *, dry_run: bool = False) -> tuple[bool, str]:
    if link.provider is None:
        return install_launcher(link, dry_run=dry_run)
    if not link.source.exists():
        return False, f"error: installation source is missing: {link.source}"
    parent_ok, parent_error = safe_parent(link.destination, link.scope)
    if not parent_ok:
        return False, f"error: cannot install {link.label}: {parent_error}"
    checkout = link.source.parents[1]
    content = bootstrap_content(checkout, link.provider)
    if link.destination.exists() and not link.destination.is_symlink() and is_owned_bootstrap(
        link.destination, checkout, link.provider
    ):
        try:
            if link.destination.read_text(encoding="utf-8") == content:
                return True, f"unchanged: {link.label}: {link.destination}"
        except OSError as error:
            return False, f"error: cannot read {link.destination}: {error}"
        if dry_run:
            return True, f"would update: {link.label}: {link.destination}"
        link.destination.write_text(content, encoding="utf-8")
        return True, f"updated: {link.label}: {link.destination}"
    if link.destination.exists() or link.destination.is_symlink():
        return False, (
            f"conflict: {link.destination} already exists; it was not replaced. "
            "Use a project-local install, add a manual one-line include, or merge "
            "the bootstrap block explicitly."
        )
    if dry_run:
        return True, f"would write: {link.label}: {link.destination}"
    link.destination.parent.mkdir(parents=True, exist_ok=True)
    link.destination.write_text(content, encoding="utf-8")
    return True, f"wrote: {link.label}: {link.destination}"


def install(links: Sequence[Link], *, dry_run: bool = False) -> tuple[bool, list[str]]:
    ok = True
    messages: list[str] = []
    for link in links:
        item_ok, message = install_link(link, dry_run=dry_run)
        ok = item_ok and ok
        messages.append(message)
    return ok, messages


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    providers = parser.add_argument_group("providers")
    providers.add_argument("--codex", action="store_true")
    providers.add_argument("--claude", action="store_true")
    scope = parser.add_mutually_exclusive_group(required=True)
    scope.add_argument("--global", dest="global_scope", action="store_true")
    scope.add_argument(
        "--project",
        nargs="?",
        const=".",
        metavar="PATH",
        help="install in PATH (defaults to the current directory)",
    )
    parser.add_argument("--launcher", action="store_true", help="also install the aih and aihui shortcuts")
    parser.add_argument("--bin-dir", type=Path, help="directory for launcher shortcuts (default: ~/.local/bin)")
    parser.add_argument("--dry-run", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    if sys.version_info < (3, 11):
        print("error: AI Code Harness requires Python 3.11 or newer", file=sys.stderr)
        return 2
    parser = _parser()
    args = parser.parse_args(argv)
    providers = [name for name in ("codex", "claude") if getattr(args, name)]
    if not providers and not args.launcher:
        parser.error("at least one of --codex, --claude, or --launcher is required")
    scope = {"home": Path.home()} if args.global_scope else {"project": Path(args.project)}
    plan: list[Link] = []
    if providers:
        plan.extend(links_for(CHECKOUT, providers, **scope))
    if args.launcher:
        plan.extend(launcher_links_for(CHECKOUT, args.bin_dir or (Path.home() / ".local" / "bin")))
    ok, messages = install(plan, dry_run=args.dry_run)
    print("\n".join(messages))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
